# Generated by Django 4.2.13 on 2024-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_summary', models.TextField()),
                ('product_pros', models.JSONField()),
                ('product_cons', models.JSONField()),
                ('product_usecase', models.JSONField()),
                ('product_toolfor', models.JSONField()),
                ('product_pricing', models.JSONField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_unique_id', models.CharField(max_length=36)),
                ('product_pricing_available', models.BooleanField(default=False)),
                ('product_affiliate_available', models.BooleanField(default=False)),
            ],
        ),
    ]
