# Generated by Django 4.2.13 on 2024-06-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareguru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='product_rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
