# Generated by Django 4.2.13 on 2024-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareguru', '0002_productdata_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='product_usecase',
            new_name='product_categories',
        ),
        migrations.AddField(
            model_name='productdata',
            name='product_url',
            field=models.URLField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdata',
            name='product_usecases',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
