# Generated by Django 4.2.13 on 2024-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareguru', '0003_rename_product_usecase_productdata_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_rating',
            field=models.FloatField(),
        ),
    ]
