# Generated by Django 4.2.13 on 2024-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareguru', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='product_featured',
            field=models.BooleanField(default=False),
        ),
    ]
