# Generated by Django 4.2.13 on 2024-06-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softwareguru', '0006_productdata_product_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('product_uuid_list', models.JSONField()),
            ],
        ),
    ]
